# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Bingo Minder CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image for bingo-minder
        run: docker build -t domzinhuu/bingo-minder:${{steps.generate_sha.outputs.sha}} .
    
      - name: Build docker image for webosocker-bingo-minder
        run: docker build -f ws.Dockerfile -t domzinhuu/ws-bingo-minder:${{steps.generate_sha.outputs.sha}} .

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push image
        run: |
          docker push domzinhuu/bingo-minder:${{steps.generate_sha.outputs.sha}}
          docker push domzinhuu/ws-bingo-minder:${{steps.generate_sha.outputs.sha}}
          docker tag domzinhuu/bingo-minder:${{steps.generate_sha.outputs.sha}} domzinhuu/bingo-minder:latest
          docker tag domzinhuu/ws-bingo-minder:${{steps.generate_sha.outputs.sha}} domzinhuu/ws-bingo-minder:latest
          docker push domzinhuu/bingo-minder:latest
          docker push domzinhuu/ws-bingo-minder:latest
      
      
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SCRIPT_AFTER: |
            docker stop bingo-minder
            docker stop ws-bingo-minder
            docker run --name bingo-minder --rm -d -p 3001:3005 domzinhuu/bingo-minder:${{steps.generate_sha.outputs.sha}}
            docker run --name ws-bingo-minder --rm -d -p 8080:8080 domzinhuu/ws-bingo-minder:${{steps.generate_sha.outputs.sha}}
  